swagger: "2.0"
info:
  version: "0.0.1"
  title: OpenOnderwijsAPI - Learning Analytics
  description: integrating learning analytics recipes
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
  /recipes:
    x-swagger-router-controller: recipes
    get:
      description: Returns list of available 'Recipes'
      tags:
        - recipes
      operationId: recipes
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/RecipesResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /recipes/{recipeId}:
    x-swagger-router-controller: recipes
    get:
      description: Returns details of 'Recipe'
      tags:
        - recipes
      operationId: recipeDetails
      parameters:
        - name: recipeId
          in: path
          required: true
          description: The id of the recipe to retrieve
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/RecipeResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /studyprogress:
    x-swagger-router-controller: studyprogress
    get:
      description: Returns studyprogress information from Learning Record Store
      tags:
        - studyprogress
        - learning analytics
        - open onderwijsapi
      operationId: studyProgress
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/StudyProgressResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /verbs:
    x-swagger-router-controller: verbs
    get:
      description: List of Verbs. The Verb defines the action between Actor and Activity
      tags:
        - learning analytics
        - open onderwijsapi
      operationId: listVerbs
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/VerbResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /object:
    x-swagger-router-controller: object
    get:
      description: The Object of a Statement can be an Activity, Agent/Group, Sub-Statement, or Statement Reference. It is the "this" part of the Statement, i.e. "I did this".
      tags:
        - learning analytics
        - open onderwijsapi
      operationId: object
      responses:
        "200":
          description: Success
          schema: 
            $ref: "#/definitions/ObjectResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /timestamp:
    x-swagger-router-controller: timestamp
    get:
      description: The time at which the experience occurred (ISO8601)
      tags:
        - learning analytics
        - open onderwijsapi
      operationId: timestamp
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/TimestampResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /statements:
    x-swagger-router-controller: statements
    get:
      description: List of xAPI statements
      tags:
        - learning analytics
        - open onderwijsapi
      operationId: listStatements
      responses:
        200:
          description: Success
          examples:
            application/json: |-

                {
                  "statements": [{
                    "id": "6ed8acd8-9f57-4cee-ba4f-3cbd07c0ebdf",
                    "actor": {
                      "objectType": "Agent",
                      "mbox": "mailto:darlene.snyder95@example.com",
                      "name": "Darlene Snyder"
                    },
                    "verb": {
                      "id": "http://adlnet.gov/expapi/verbs/attempted",
                      "display": {
                        "en-US": "attempted"
                      }
                    },
                    "object": {
                                "id": "http://adlnet.gov/expapi/activities/course",
                                "objectType": "Activity",
                                "definition": {
                                    "name": {
                                        "en-US": "course"
                                    },
                                    "description": {
                                        "en-US": "course"
                                    }
                                }
                            },
                            "stored": "2016-01-19T14:06:11Z"
                        }, {
                            "id": "bf7daae7-ba14-4605-8c6e-7fc25d72190b",
                            "actor": {
                                "objectType": "Agent",
                                "mbox": "mailto:melvin.patterson48@example.com",
                                "name": "Melvin Patterson"
                            },
                            "verb": {
                                "id": "http://adlnet.gov/expapi/verbs/imported",
                                "display": {
                                    "en-US": "imported"
                                }
                            },
                            "object": {
                                "id": "http://adlnet.gov/expapi/activities/module",
                                "objectType": "Activity",
                                "definition": {
                                    "name": {
                                        "en-US": "module"
                                    },
                                    "description": {
                                        "en-US": "module"
                                    }
                                }
                            },
                            "stored": "2016-01-19T14:06:12Z"
                        }]
                    }

          schema:
            $ref: "#/definitions/StatementsResponse"
          
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Create statement
      tags:
        - learning analytics
        - open onderwijsapi
      operationId: createStatement
      
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"        
  /statements/{statementId}:
    x-swagger-router-controller: statements
    get:
      description: Get statement based on statementId
      tags:
        - learning analytics
        - open onderwijsapi
      operationId: getStatementById
      parameters:
        - name: statementId
          in: path
          required: true
          description: The id of the statement to retrieve
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/StatementByIdResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  RecipesResponse:
    required:
      - message
    properties:
      message:
        type: string
  RecipeResponse:
    required:
      - recipeId
    properties:
      recipeId:
        type: string
  VerbResponse:
    required:
      - id
    properties:
      id:
        type: string
      display:
        type: object
        description: "Key - value pair, where key is language code (as RFC 5646 Language Tag) and value is the human readable representation of the Verb in one or more languages., e.g. \"en_US\": \"mastered\""
      label:
        type: string
      description:
        type: string
        # language map rfc5646
  StudyProgressResponse:
    required:
      - message
    properties:
      message:
        type: string
  ObjectResponse:
    required:
      - objectType
    properties:
      objectType:
        type: string
      id:
        type: string
  TimestampResponse:
    required:
      - message
    properties:
      message:
        type: string
  StatementsResponse:
    properties:
      statements:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            actor:
              type: object
              properties:
                mbox:
                  type: string
  StatementByIdResponse:
    properties:
      message:
        type: string
  
      
      
      
